Repository Arquisoft/wichat_en3b, pull requests merged in 2025-04, with the labels that each got.

#98 Question service tests
  questionservice/package.json
  questionservice/test/wikidata-service.test.js
  questionservice/wikidata-service.js
Labels: test

#104 Set CI to false to ignore warnings during build
  .github/workflows/release.yml
Labels: bug

#112 Trying to fix continuous integration
  .github/workflows/release.yml
  docker-compose.yml
  gatewayservice/Dockerfile
  llmservice/Dockerfile
  users/authservice/auth-service.js
  webapp/Dockerfile
Labels: bug

#140 Phone integration
  package-lock.json
  package.json
  webapp/src/components/AddUser.js
  webapp/src/components/Game.js
  webapp/src/components/Login.js
  webapp/src/components/phone/Contacts.js
  webapp/src/components/phone/PhoneDialog.js
  webapp/src/components/photos/logInPic.png
Labels: enhancement

#149 Making QuestionService follow REST.
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  gatewayservice/openapi.yaml
  llmservice/llm-service.test.js
  questionservice/test/wikidata-service.test.js
  questionservice/wikidata-model.js
  questionservice/wikidata-service.js
  users/userservice/game-model.js
  users/userservice/user-service.js
  users/userservice/user-service.test.js
  users/userservice/user-statistic-model.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.test.js
  webapp/src/components/Game.js
  webapp/src/components/Game.test.js
  webapp/src/components/GameTopicSelection.js
  webapp/src/components/GameTopicSelection.test.js
  webapp/src/components/Home.js
  webapp/src/components/Home.test.js
  webapp/src/components/LLMChat.js
Labels: bug, enhancement

#151 Localization and added SignUp link
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/App.test.js
  webapp/src/components/AddUser.js
  webapp/src/components/AddUser.test.js
  webapp/src/components/LanguageSelect.js
  webapp/src/components/Layout.js
  webapp/src/components/Layout.test.js
  webapp/src/components/Login.js
  webapp/src/components/Login.test.js
  webapp/src/hooks/useAxios.js
  webapp/src/hooks/useRefreshToken.js
  webapp/src/index.js
  webapp/src/locales/translation_en.json
  webapp/src/locales/translation_es.json
  webapp/src/utils/axios.js
  webapp/src/utils/i18n.js
Labels: enhancement

#150 Fixed an issue with the accumulated UserStatistics for all topics
  users/userservice/user-service.js
Labels: bug

#152 Various Fixes
  webapp/src/components/AddUser.js
  webapp/src/components/CustomTextField.js
  webapp/src/components/LanguageSelect.js
  webapp/src/components/Login.js
Labels: bug

#160 Home userstats revamp
  gatewayservice/gateway-service.js
  users/userservice/user-service.js
  webapp/src/components/Home.js
  webapp/src/index.js
Labels: enhancement

#163 Webapp themes
  webapp/src/App.js
  webapp/src/App.test.js
  webapp/src/components/AddUser.js
  webapp/src/components/AddUser.test.js
  webapp/src/components/CustomTextField.js
  webapp/src/components/Game.js
  webapp/src/components/Game.test.js
  webapp/src/components/GameModeSelection.js
  webapp/src/components/GameModeSelection.test.js
  webapp/src/components/GameTopicSelection.js
  webapp/src/components/GameTopicSelection.test.js
  webapp/src/components/Home.js
  webapp/src/components/Home.test.js
  webapp/src/components/LLMChat.js
  webapp/src/components/LanguageSelect.js
  webapp/src/components/Layout.js
  webapp/src/components/Layout.test.js
  webapp/src/components/Login.js
  webapp/src/components/Login.test.js
  webapp/src/components/Welcome.test.js
  webapp/src/context/ThemeContext.js
  webapp/src/hooks/useTheme.js
  webapp/src/index.js
Labels: enhancement

#168 Enhacement of the Topic Selection and the Language menu drop
  webapp/src/components/GameTopicSelection.js
  webapp/src/components/GameTopicSelection.test.js
  webapp/src/components/LanguageSelect.js
Labels: enhancement

#172 Settings dialog
  llmservice/llm-service.js
  llmservice/llm-service.test.js
  webapp/src/components/LLMChat.js
  webapp/src/components/LanguageSelect.js
  webapp/src/components/Layout.js
  webapp/src/components/SettingsDialog.js
  webapp/src/components/SettingsDialog.test.js
  webapp/src/context/ThemeContext.js
Labels: enhancement

#185 Add mode to home and ranking
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  users/userservice/game-model.js
  users/userservice/user-service.js
  users/userservice/user-service.test.js
  users/userservice/user-statistic-model.js
  webapp/src/components/Home.js
  webapp/src/components/Home.test.js
  webapp/src/components/game/BaseGame.js
  webapp/src/components/game/BaseGame.test.js
  webapp/src/components/game/HideGame.js
  webapp/src/components/game/RoundsGame.js
  webapp/src/components/game/TimeGame.js
Labels: bug, enhancement

#192 Added functionality for the application to be more keyboard-friendly
  webapp/package-lock.json
  webapp/src/App.js
  webapp/src/components/AddUser.js
  webapp/src/components/login/Login.js
Labels: enhancement

#195 Fixed multiple bugs
  webapp/src/App.js
  webapp/src/components/AddUser.js
  webapp/src/components/AddUser.test.js
  webapp/src/components/LanguageSelect.js
  webapp/src/components/game/BaseGame.js
  webapp/src/components/game/RoundsGame.js
  webapp/src/components/login/Login.js
  webapp/src/components/login/Login.test.js
  webapp/src/index.js
  webapp/src/utils/i18n.js
Labels: bug

#194 Unitary tests
  questionservice/test/wikidata-service.test.js
  questionservice/wikidata-service.js
  questionservice/wikidata-service.test.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/game/BaseGame.js
  webapp/src/components/game/BaseGame.test.js
  webapp/src/components/selections/GameTopicSelection.test.js
  webapp/src/handlers/LifeLinesHandler.js
Labels: test

#201 Fixed one bug and added Gemini to the LLMs
  .github/workflows/release.yml
  docker-compose.yml
  llmservice/Dockerfile
  llmservice/llm-service.js
  llmservice/llm-service.test.js
  webapp/src/components/AddUser.js
  webapp/src/components/SettingsDialog.js
  webapp/src/components/login/Login.js
Labels: bug, enhancement

#200 Internationalization
  webapp/src/App.js
  webapp/src/components/Home.js
  webapp/src/components/Home.test.js
  webapp/src/components/SettingsDialog.js
  webapp/src/components/SettingsDialog.test.js
  webapp/src/locales/translation_en.json
  webapp/src/locales/translation_es.json
Labels: enhancement

#204 Mode selection enhancement
  webapp/src/components/Home.js
  webapp/src/components/selections/GameModeSelection.js
  webapp/src/components/selections/GameModeSelection.test.js
  webapp/src/components/selections/SelectionStyles.js
Labels: enhancement

#199 Phone integration
  webapp/src/components/game/BaseGame.js
  webapp/src/components/game/BaseGame.test.js
  webapp/src/components/lifelines/GraphComponent.js
  webapp/src/components/phone/Contacts.js
  webapp/src/components/phone/FriendChat.js
  webapp/src/components/phone/FriendChat.test.js
  webapp/src/components/phone/PhoneDialog.js
  webapp/src/components/phone/PhoneDialog.test.js
  webapp/src/components/photos/lockedPic.png
  webapp/src/handlers/LifeLinesHandler.js
Labels: enhancement

#206 Final front touches + New lifeline + Adjustment on coins
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/game/BaseGame.js
  webapp/src/components/game/GameStyles.js
  webapp/src/components/lifelines/CallFriend.js
  webapp/src/components/lifelines/CallFriend.test.js
  webapp/src/components/lifelines/CharacterSelection.js
  webapp/src/handlers/LifeLinesHandler.js
Labels: enhancement

#215 Documentation
  docs/images/brain_logo.jpg
  docs/index.adoc
  docs/src/03_context_and_scope.adoc
  docs/src/05_building_block_view.adoc
  docs/src/06_runtime_view.adoc
  docs/src/07_deployment_view.adoc
  docs/src/11_technical_risks.adoc
Labels: documentation

#218 Localization of Topics Page and UI Improvement
  webapp/e2e/steps/game-select.steps.js
  webapp/package-lock.json
  webapp/src/components/selections/GameTopicSelection.js
  webapp/src/components/selections/GameTopicSelection.test.js
  webapp/src/locales/translation_en.json
  webapp/src/locales/translation_es.json
Labels: enhancement, test

#210 Coins for the chat.
  webapp/src/components/game/BaseGame.js
  webapp/src/components/phone/FriendChat.js
  webapp/src/components/phone/PhoneDialog.js
  webapp/src/components/phone/PhoneDialog.test.js
  webapp/src/handlers/LifeLinesHandler.js
  webapp/src/handlers/LifeLinesHandler.test.js
Labels: enhancement

#222 Improved dashboard and try to fix release
  .github/workflows/release.yml
  gatewayservice/gateway-service.js
  gatewayservice/monitoring/grafana/provisioning/dashboards/example-service-dashboard.json
  gatewayservice/monitoring/grafana/provisioning/dashboards/gateway-service-dashboard.json
Labels: bug, enhancement

#223 Trying to fix e2e tests to be consistent in GitHub actions
  .github/workflows/build.yml
  webapp/e2e/features/game-select.feature
  webapp/e2e/features/register-form.feature
  webapp/e2e/steps/game-select.steps.js
  webapp/e2e/steps/login-form.steps.js
  webapp/e2e/steps/register-form.steps.js
  webapp/e2e/steps/settings-navigation.steps.js
  webapp/e2e/test-helper.js
Labels: bug

#237 Changing CORS setup to allow all origins from the server's hostname
  gatewayservice/gateway-service.js
Labels: bug
